### ISSUE TITLE
Flurry SDK not available

### ISSUE THREAD

**Issue by BojanKogoj** [thurask/bbdownloader#1]
Cannot create a new BlackBerry project on Flurry, therefore unable to build it.

**Comment by thurask** [comment]
Sent request to Flurry support, although I don't have my hopes up.

**Comment by thurask** [comment]
Tim Beckler (Flurry Support)
May 19, 15:03

Hello,

Thank you for contacting Flurry Technical Support. I will be happy to answer your questions.

Yes, I'm afraid the BlackBerry SDK has been EOL.

However, you should be able to create a new Android or Apple app, then use the provided API key for your new BlackBerry app using the same SDK 2.0 as your other BB app. The icon in the dashboard will display whatever platform you chose, but I can fix that on our end afterward.

Please let me know if I can assist further.

Regards,

Tim

Flurry, Inc.
support@flurry.com

**Comment by thurask** [comment]
I guess I should provide [this copy of the SDK](https://drive.bitcasa.com/send/KrKsDGU4ggXNehpck8k9iVpY8vU5Edfiq3-s3BC1GTs7) for future use.
